# Generated by Django 3.1.2 on 2020-10-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_type',
            fields=[
                ('news_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Source_Details',
            fields=[
                ('source_details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rss_feed_url', models.CharField(max_length=500)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='News_data',
            fields=[
                ('news_data_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_date', models.DateField()),
                ('news_data', models.CharField(max_length=100)),
                ('news_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news_type')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=100)),
                ('article_data', models.TextField()),
                ('news_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news_data')),
            ],
        ),
    ]
